### ISSUE TITLE
IOError: [errno 2: no such file or directory: "bruno.jpg"

### ISSUE THREAD

**Issue by crypticneo13** [brunocenteno/face_recognition_video_tutorial#1]
im doing this in my actual linux pc i use where should i put the files since im not using a virtual enviroment

**Comment by rahulmasterincoding** [comment]
you have to create a folder under that and make sure that a file is already present in that same directory named bruno.jpg
😶😶😶😶

**Comment by NanoLine** [comment]
You can create your own bruno.jpg picture. It will be work after it.

**Comment by brunocenteno** [comment]
Yes, make sure you have an image with the name bruno.jpg if you are running the script as it is. 
Otherwise, feel free to use another picture and use the name of the picture you are using.

**Comment by brunocenteno** [comment]
Put the picture in the same folder as the script or use the full path to the picture
